In [1]:
import datetime
datetime.datetime.now()

datetime.datetime(2019, 11, 21, 9, 45, 49, 928298)

In [4]:
d=datetime.datetime.now()
d

datetime.datetime(2019, 11, 21, 9, 51, 14, 603290)

In [6]:
d

datetime.datetime(2019, 11, 21, 9, 51, 14, 603290)

In [8]:
d.day

21

In [9]:
d.month

11

In [10]:
d.year

2019

In [12]:
d.minute

51

In [14]:
d.weekday

<function datetime.weekday>

In [15]:
d.date

<function datetime.date>

In [16]:
d.date()

datetime.date(2019, 11, 21)

In [19]:
import datetime as dt
d=dt.datetime.now()
d.weekday()

3

In [20]:
dir(d)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'astimezone',
 'combine',
 'ctime',
 'date',
 'day',
 'dst',
 'fold',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'now',
 'replace',
 'resolution',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'today',
 'toordinal',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'weekday',
 'year']

In [25]:
import calendar as c
cal=c.month(2019,11)
print(cal)

   November 2019
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



In [26]:
cal

'   November 2019\nMo Tu We Th Fr Sa Su\n             1  2  3\n 4  5  6  7  8  9 10\n11 12 13 14 15 16 17\n18 19 20 21 22 23 24\n25 26 27 28 29 30\n'

In [34]:
cal=c.monthrange(2019,12)
cal

(6, 31)

In [36]:
cal=c.weekday(2019,11,15)
cal

4

In [37]:
d.max

datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)

In [38]:
d.isocalendar

<function datetime.isocalendar>

In [39]:
d.isoformat()

'2019-11-21T09:57:05.907333'

In [40]:
d.dst

<function datetime.dst>

In [43]:
import time
localtime=time.localtime(time.time())
localtime

time.struct_time(tm_year=2019, tm_mon=11, tm_mday=21, tm_hour=10, tm_min=30, tm_sec=21, tm_wday=3, tm_yday=325, tm_isdst=0)

In [44]:
from datetime import date
today=date.today()
today

datetime.date(2019, 11, 21)

In [45]:
d.today()

datetime.datetime(2019, 11, 21, 10, 31, 47, 530019)

In [46]:
datetime.date(2019,11,21)

datetime.date(2019, 11, 21)

In [48]:
d1=today.strftime("%d%B%y")
d1

'21November19'

In [49]:
d1=today.strftime("%d%b%y")
d1

'21Nov19'

In [53]:
d1=today.strftime("%d %m %y")
d1

'21 11 19'

In [ ]:
from tkinter import *
tk=Tk()
canvas=Canvas(tk,width=400,height=400)
canvas.pack()
canvas.create_arc(10,10,200,100,extent=180,style=ARC)
tk.mainloop()

In [ ]:
import turtle
t=turtle.Pen()
t.color

### Data Analysis libraries
- Numpy
- Scipy
- Pandas
- SciKit-Learn
### Visualization Tools
- matplot lib
- Seaborn
- Plotly

gotapway.com

In [4]:
import numpy as np
d=np.random.randn(2,3)
print(d)

[[ 1.70663334 -0.28535203 -1.07662618]
 [ 0.31036009  0.31760467  1.55410812]]


In [7]:
d*10

array([[ 17.06633344,  -2.85352033, -10.76626179],
       [  3.10360091,   3.17604667,  15.54108118]])

In [8]:
d+d

array([[ 3.41326669, -0.57070407, -2.15325236],
       [ 0.62072018,  0.63520933,  3.10821624]])

In [9]:
d-d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
a=np.array([[1,2,3],[6,7,8]])
a

array([[1, 2, 3],
       [6, 7, 8]])

In [11]:
a*a

array([[ 1,  4,  9],
       [36, 49, 64]])

In [12]:
a-a

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
1/a

array([[1.        , 0.5       , 0.33333333],
       [0.16666667, 0.14285714, 0.125     ]])

In [14]:
a**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.44948974, 2.64575131, 2.82842712]])

In [15]:
a2=np.array([[0,4,1],[7,2,12]])
a2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [16]:
a2>a

array([[False,  True, False],
       [ True, False,  True]])

In [17]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a[5]

5

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a[5:8]

array([5, 6, 7])

In [21]:
a[5:8]=12
a

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [22]:
a[1:6]


array([ 1,  2,  3,  4, 12])

### python-2:print is keyword
### python-3:print is function

In [23]:
a=a[5:8]
a

array([12, 12, 12])

In [24]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a2[:2,:]









array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a2[:2,1:]

array([[2, 3],
       [5, 6]])

In [27]:
a2[:,1:2]

array([[2],
       [5],
       [8]])

In [28]:
a2[1,:2]

array([4, 5])

In [29]:
a2[:2,2]

array([3, 6])

In [30]:
a2[:,:1]

array([[1],
       [4],
       [7]])

In [31]:
a2[:2,1:]=0
a2

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [32]:
names=np.array(['bob','joe','will','bob','will','joe','joe'])
data=np.random.randn(7,4)
names=='bob'
data[names=='bob']
data[names=='bob',2:]
data[names=='bob',3:]

array([[1.20423691],
       [2.85970832]])

In [33]:
data[names=='bob',1:]


array([[ 0.79294992,  1.71293655,  1.20423691],
       [-0.41169054,  1.86874814,  2.85970832]])

In [34]:
data

array([[-6.00323422e-01,  7.92949919e-01,  1.71293655e+00,
         1.20423691e+00],
       [ 1.58929792e+00,  1.68612565e+00, -1.42278791e+00,
        -1.25403662e+00],
       [-1.21569139e+00, -2.50513005e-01, -1.92497388e+00,
        -1.13044576e-01],
       [ 4.65828936e-01, -4.11690541e-01,  1.86874814e+00,
         2.85970832e+00],
       [-9.15414718e-01, -4.17612765e-01, -2.25946829e+00,
         2.97461983e-01],
       [-5.40639103e-01,  5.60090800e-01,  1.60828295e-01,
        -8.23898742e-01],
       [-1.72473214e-03, -1.04084111e+00,  5.65859175e-01,
         1.00601514e+00]])

In [35]:
mask=(names=='bob')|(names=='will')
mask

array([ True, False,  True,  True,  True, False, False])

In [36]:
data[mask]

array([[-0.60032342,  0.79294992,  1.71293655,  1.20423691],
       [-1.21569139, -0.25051301, -1.92497388, -0.11304458],
       [ 0.46582894, -0.41169054,  1.86874814,  2.85970832],
       [-0.91541472, -0.41761276, -2.25946829,  0.29746198]])

In [37]:
data[data<0]=0
data

array([[0.        , 0.79294992, 1.71293655, 1.20423691],
       [1.58929792, 1.68612565, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.46582894, 0.        , 1.86874814, 2.85970832],
       [0.        , 0.        , 0.        , 0.29746198],
       [0.        , 0.5600908 , 0.1608283 , 0.        ],
       [0.        , 0.        , 0.56585918, 1.00601514]])

In [38]:
data[names!='joe']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.58929792, 1.68612565, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.5600908 , 0.1608283 , 0.        ],
       [0.        , 0.        , 0.56585918, 1.00601514]])

In [39]:
a=np.empty((8,4))
for i in range(8):
    a[i]=i
print(a)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [40]:
a[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [41]:
a[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [42]:
a=np.arange(32).reshape((8,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [57]:
a[[1,5,7,2],[0,3,1,2]]
a

IndexError: index 5 is out of bounds for axis 0 with size 2

In [56]:
a[[1,5,7,2]][:,[0,3,1,2]]

IndexError: index 5 is out of bounds for axis 0 with size 2

In [45]:
np.dot(a.T,a)


array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [46]:
a=np.arange(16).reshape((2,2,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [47]:
a.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [48]:
a.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [49]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [50]:
a.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

#### PANDAS
- Series
- Data Frames

In [59]:
import pandas as pd
x=pd.Series([4,7,-5,3])
x

0    4
1    7
2   -5
3    3
dtype: int64

In [63]:
x.values

array([ 4,  7, -5,  3], dtype=int64)

In [64]:
x.index

RangeIndex(start=0, stop=4, step=1)

In [72]:
x1=pd.Series([4,7,-5,3],index=['1','b','c','d'])
x1

1    4
b    7
c   -5
d    3
dtype: int64

In [66]:
x1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [67]:
x1.values

array([ 4,  7, -5,  3], dtype=int64)

In [68]:
x1['b']

7

In [69]:
x1[['c','b']]

c   -5
b    7
dtype: int64

In [70]:
x1[x1>0]

a    4
b    7
d    3
dtype: int64

In [71]:
x1*2

a     8
b    14
c   -10
d     6
dtype: int64

In [73]:
np.exp(x1)

1      54.598150
b    1096.633158
c       0.006738
d      20.085537
dtype: float64

In [75]:
'b'in x1

True

In [76]:
'e' in x1

False

In [77]:
s={'a':300,'b':400,'c':500}
d=pd.Series(s)
d

a    300
b    400
c    500
dtype: int64

In [89]:
d={'a':300,'b':400,'c':500}
d1=pd.Series(d)
d1

a    300
b    400
c    500
dtype: int64

In [102]:
states={'california':4000,'ohio':500,'orenfo':4000,'china':1233}
x4=pd.Series(states)
x4

california    4000
ohio           500
orenfo        4000
china         1233
dtype: int64

In [103]:
pd.isnull(x4)

california    False
ohio          False
orenfo        False
china         False
dtype: bool

In [104]:
pd.notnull(x4)

california    True
ohio          True
orenfo        True
china         True
dtype: bool

In [105]:
d1

a    300
b    400
c    500
dtype: int64

In [107]:
d1+x4

a            NaN
b            NaN
c            NaN
california   NaN
china        NaN
ohio         NaN
orenfo       NaN
dtype: float64